### PR TITLE
Updated tests/expectations for oriscus scapus direction changes.

### PR DESCRIPTION
**Pull request by henryso**
Includes tests for coverage of these changes.
Tests the version 4.1 part of gregorio-project/gregorio#898.
Corresponds with gregorio-project/gregorio#917.

### CODE REVIEW

**Comment by eroux** [comment]
There's one thing I don't understand: in [shape_switching](https://github.com/henryso/gregorio-test/blob/fix-898-4.1/tests/gabc-dump/glyphs/shape_switching.pdf), why is `gO0r` upwards?

**Comment by henryso** [comment]
That would be a bug.

**Comment by henryso** [comment]
I'll look into this later tonight.  I'll have something by your morning.

**Comment by eroux** [comment]
Ok, apart from that everything seems good (including the code/doc review)

**Comment by henryso** [comment]
That was a silly mistake.  I literally had O0 and O1 swapped.

**Comment by eroux** [comment]
Good! Let's merge, thanks a lot for this!

**Pull request merged**
