### PR TITLE
New test which demonstrates the various line shift settings

### PR DESCRIPTION
**Pull request by rpspringuel**

### CODE REVIEW

**Comment by henryso** [comment]
`gabc-output/glyphs/clef_change.gabc` is still apparently different:

diff-page

**Comment by rpspringuel** [comment]
I know that test passed on my computer yesterday, but I'll look at it again when I get home.

**Comment by rpspringuel** [comment]
Okay, I've double checked and on my machine all the tests in this PR pass on d6236ce (the last commit on the 584-2 branch) and 937ddf8 (the most recent commit on develop).

**Comment by henryso** [comment]
I did a clean checkout of origin from github, and it still fails in the exact same way.  Could it be a difference due to TeX Live?  My distribution is still on 2014.

**Comment by rpspringuel** [comment]
That does appear to be the problem.  When I switch my TeX distribution back to TeXLive 2014 I get the same thing you do.

How do you want to handle this?  In 2014 the expanded test doesn't show what I want it to show because of the differences in the spacing.

**Comment by henryso** [comment]
We'll take your result, and I'll ignore that error on my system until my distribution upgrades to 2015.

**Comment by eroux** [comment]
I think this is due to a bug in LuaTeX in TeXLive 2014 that was workedaround by a strange useless line somewhere in GregorioTeX and it got removed in the 584-2 branch

**Comment by henryso** [comment]
Ideally, then, if we can figure out which line that is, we should try to restore it.  TeX Live 2014 is not all that old yet.

**Comment by eroux** [comment]
I think it's [this one](https://github.com/gregorio-project/gregorio/commit/eefba9bb92d36fccfd2686ae42a3d1f87bea8615#commitcomment-13233497)

**Comment by rpspringuel** [comment]
Perhaps this is related to the code in `gsp-default.tex` that is LuaTeX version dependent?  Recall that techinically according to the bug report for LuaTeX we should have set the boundry at v0.80, but we set it earlier (v0.78) because it breaks a whole bunch of tests if TeXLive 2014 and TeXLive 2015 are on opposite sides of the boundry.  However, that code is supposed to affect discretionaries (which the clef change test has several of)  so this difference could be an example of that bug in action.

**Comment by henryso** [comment]
Since the "fix" breaks other (and more) tests, I think we should just leave things as-is, as of now.  I will ignore this test breaking until I (or my distribution) upgrade to 2015.

**Pull request merged**
