### PR TITLE
add more edge case tests to bar spacing tests

### PR DESCRIPTION
**Pull request by eroux**
I still think these tests are quite useful...

### CODE REVIEW

**Comment by henryso** [comment]
These tests are probably useful, but need conflict resolution.

**Comment by henryso** [comment]
@eroux I merged develop into this branch.  Please review it and merge it if you still want these new tests to be added.  I am really not the best person to judge the new spacing algorithm.

**Comment by eroux** [comment]
Well, the problem is that the PR is against release-4.1... I'll try to clean this tomorrow, thanks!

**Comment by henryso** [comment]
I can fix that.

**Pull request closed without merging**
