### PR TITLE
Ctan

### PR DESCRIPTION
**Pull request by rpspringuel**
Corresponds to gregorio-project/gregorio#1210

Note: I'm still double checking these test results against TL2015.  With these changes we have a full pass on (updated) TL2016.

### CODE REVIEW

**Comment by rpspringuel** [comment]
I've checked backwards compatibility of the tests and I get no failures with TL2015 and only one with TL2014.  Interestingly, the TL2014 failure isn't one of the previously known failures.  Both of those pass, but the double-clef test fails (though along the same lines as the previously known failures: in the line breaking choices).  Should I edit the README to note the change in known failures?

**Comment by henryso** [comment]
I suppose we have three options:

1. Say that this version of Gregorio requires TeX Live 2015, or
2. Say that double clefs are only supported from TeX Live 2015
3. Try to fix the problem in TeX Live 2014.

**Comment by eroux** [comment]
I would be in favor of option 1...

**Comment by rpspringuel** [comment]
Well, it's not that the double clefs don't work with TL2014, it simply that the line breaking decisions in TL2014 are slightly different and this results in the test failing.  We had this same problem with two other tests before (clef_change and fix-508), but those differences seem to have gone away now (probably due to some space tuning somewhere that results in the line break decision being more "obvious").  My inclination is simply to update the list of known failures in TL2014 (in README.md).  It's only those running the tests that will likely really worry about this.

**Comment by henryso** [comment]
In that case, I would just note that line breaking decisions are different in TeX Live 2014 and leave it at that.

**Pull request merged**
