### PR TITLE
Updated expectations to match changes for gregorio-project/gregorio#670.

### PR DESCRIPTION
**Pull request by henryso**
Tests changes for gregorio-project/gregorio#670.
Corresponds with gregorio-project/gregorio#673.

### CODE REVIEW

**Comment by rpspringuel** [comment]
Question: should we add some tests which make sure that the gabc output capabilities of the command-line tool work as expected?

**Comment by henryso** [comment]
I suppose the answer is yes, but the gabc writing has been broken for some time now, missing several constructions (going back to early 2.x days) that were added to gregorio (and obviously gregoriotex-write) but not to gabc-write.  I'll admit to not being very motivated to correct these old bugs for this little-used feature.

**Comment by henryso** [comment]
I added the gabc-to-gabc tests.  Apologies for taking so long.

**Comment by rpspringuel** [comment]
Quite all right.  I've been too busy to review the outstanding pull requests any way.  I've got off from school on Wednesday, so hopefully I'll be able to find some time then to take a look and see what's what.

**Pull request merged**
