### PR TITLE
Accepting revised tests due to change of default bar spacing algorithm

### PR DESCRIPTION
**Pull request by rpspringuel**
Corresponds to gregorio-project/gregorio#991

### CODE REVIEW

**Comment by rpspringuel** [comment]
Got it.

**Comment by rpspringuel** [comment]
Got it.

**Comment by rpspringuel** [comment]
I'm re-running the tests due to the conflict to make sure everything is kosher.  When that's done I'll merge the remaining PRs and build the release (unless someone stops me).

**Comment by eroux** [comment]
sure, please do, thanks a lot!

**Pull request merged**
