### PR TITLE
Feature/bar spacing

### PR DESCRIPTION
**Pull request by rpspringuel**
Corresponds to gregorio-project/gregorio#864.

### CODE REVIEW

**Comment by eroux** [comment]
Thanks, it looks better!I was just confused by the `effectively no offset limit`, I guess this means "offset limit = +infinite", while I thought it meant "offset limit = 0pt" when first reading it. Apart from this small detail I think it's ready to merge, we can modify some default values in beta3 (or rc1!)

**Comment by eroux** [comment]
Another non-blocking comment: in your examples, it's a bit difficult to know which syllable is which, as they're all mainly `t` and have no sense, maybe it would be easier to read with very different letters, or numbers?

**Comment by rpspringuel** [comment]
Do those changes help?

**Comment by eroux** [comment]
Indeed, thanks!

**Pull request merged**
