### PR TITLE
Small inconsistency

### PR DESCRIPTION
**Pull request by rpspringuel**
I found this small test inconsistency while preparing the next release candidate for 4.2.  I have not yet had the chance to try and figure out what's causing it, but it's seems to be just a minor font or spacing difference.

### CODE REVIEW

**Comment by eroux** [comment]
This one doesn't compile on my system anyway... so nothing against the merge!

**Comment by henryso** [comment]
@rpspringuel I can't get luatex-ja to work on my computer either, so if you feel this is good to merge, then please feel free.

**Comment by rpspringuel** [comment]
If this test doesn't compile for either of you, perhaps we should create a set of "optional" tests where tests with known special requirements (like this one) can be placed so that they don't gum up the normal test results.

**Comment by henryso** [comment]
I added a way to skip tests for this purpose, by setting the SKIP_TESTS variable in gregorio-test.rc:
```
SKIP_TESTS=(
    plain-tex/luatex-ja/PopulusSion.tex
)
```

**Comment by rpspringuel** [comment]
Well, if the mechanism already exists, then there's nothing else to worry about.

**Pull request merged**
