### PR TITLE
Adding some clarity to the docs here

### PR DESCRIPTION
**Pull request by rpspringuel**

### CODE REVIEW

**Comment by henryso** [comment]
My intention is that, once 4.0.0 becomes master, I will branch develop, so both repositories will have master and develop and will coincide with each other.

**Comment by rpspringuel** [comment]
Ah!  That makes a whole lot more sense.  I'll edit this PR and then we can leave it waiting in the wings for when 4.0.0 goes live.

**Comment by henryso** [comment]
@rpspringuel I thought you were going to leave this waiting in the wings?

**Comment by rpspringuel** [comment]
It still is, I just needed it off my master branch so that I could move forward with the repository tests.  I renamed the branch to v4.0.0 and then recreated my master branch, but I guess that the changes didn't get conveyed to the pull request properly.  I'll open a new one which points to the new branch.

**Pull request closed without merging**
