### PR TITLE
Added and updated tests for the ledger line change.

### PR DESCRIPTION
**Pull request by henryso**
Tests gregorio-project/gregorio#1215.
Corresponds with gregorio-project/gregorio#1232.

### CODE REVIEW

**Comment by eroux** [comment]
Generally speaking, the code changes look ok to me and we can delay the feature of the clivis, but I cannot see any change in https://github.com/henryso/gregorio-test/blob/a89b6be327ec8585c6e24f3b7d0f1539a0b57c93/tests/gabc-output/bugs/fix-1215.pdf which still looks the same as what was reported in #1215 ... ?

**Comment by henryso** [comment]
dd and ee are different, but you're right; in going back and forth, I lost the fix for bb and cc.  I'll work on it, but I'm not sure I'll be able to complete it this weekend.

**Comment by eroux** [comment]
ok, no hurry!

**Comment by henryso** [comment]
The fix is in.  Please review.

**Comment by eroux** [comment]
Looks perfect, thanks!

**Pull request merged**
