### PR TITLE
Null? results

### PR DESCRIPTION
**Pull request by rpspringuel**
I don’t know why these files are being flagged as test failures on my machine, as the diff files appear to show identical files.  Please check these on other machines to see if what is going on can be determined.

### CODE REVIEW

**Comment by henryso** [comment]
Please try this again with the changes from #300.

**Comment by rpspringuel** [comment]
I'm still getting the pseudo-failures.

**Comment by henryso** [comment]
Thanks for checking.  These are not flagged on my system.  Maybe I need to change the compare command.  I'm not sure when I'll have time to look into it, but I'll leave this here as a reminder.

**Comment by henryso** [comment]
Can you try deleting the images for those tests from your image cache (in `var/image-cache`) and see if that fixes the problem?

**Comment by rpspringuel** [comment]
A fresh image doesn't help.

**Comment by henryso** [comment]
One last question: what does (imagemagick) `compare --version` return?

**Comment by rpspringuel** [comment]
```
Version: ImageMagick 6.9.7-5 Q16 x86_64 2017-01-29 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules 
Delegates (built-in): bzlib djvu fftw fontconfig freetype gslib jbig jng jp2 jpeg lcms ltdl lzma openexr png ps tiff webp x xml zlib
```

**Comment by henryso** [comment]
I can't explain why these differ on comparison on your system, but they don't differ on mine, so let's just merge it and move on.

**Pull request merged**
