### PR TITLE
Implement adjustable test threshold

### PR DESCRIPTION
**Pull request by rpspringuel**
Adds a new user settable parameter `THRESHOLD` which determines how strict the comparison has to be to pass an image comparison test.  `THRESHOLD` takes on values of 0 to 1 with a 1 being a perfect pixel-by-pixel match.
To facilitate this new setting, test of comparison result `metric` vs. `THRESHOLD` is now done using `bc` for floating point precision.  This replaces previous coercion of value to integer (round to 3 decimal places and multiply by 1000) which enabled `bash`'s internal integer comparison operators to do the test.
The default value of 0.9985 is designed to imitate the previous test limit of 999 (it's the smallest value that would be coerced to 999).

### CODE REVIEW

**Comment by rpspringuel** [comment]
There are also a couple of tests which are updated in this PR.

`gabc-output/glyphs/pitches` was actually failing at 300dpi (but not at 150dpi, where I usually run my tests) before the change and thus continued to fail with the default value for `THRESHOLD`

`gabc-output/glyphs/broken_shapes` -- This test changed due to the new oriscus direction logic, but the change is only to one glyph and thus was missed before(see gregorio-project/gregorio#1412).  A `THRESHOLD` value of 0.998632 was required to catch the difference at 300dpi.  The difference could also be caught at 150dpi, but would require a `THRESHOLD` of 0.998747.

**Comment by henryso** [comment]
I think THRESHOLD is too general and should be something more specific like IMAGE_COMPARE_THRESHOLD.  Have you tried comparing same version of TeX Live across different operating systems?  That's the reason compare is using a fuzzy number (i.e., not a 100% match).  Also realize that calling out bc is around 100 times slower than using something built-in to the scripting language (and around 10 times slower than something that uses floating point rather than infinite precision registers), which due to your machine, was the reason I didn't use bc in the first place.

**Comment by rpspringuel** [comment]
> I think THRESHOLD is too general and should be something more specific like IMAGE_COMPARE_THRESHOLD.

Easy enough to change.

> Have you tried comparing same version of TeX Live across different operating systems? That's the reason compare is using a fuzzy number (i.e., not a 100% match).

**Comment by henryso** [comment]
If you didn't notice a performance problem, then that's good enough for me.  Maybe one day, the harness could be rewritten in a scripting language that can access libraries to do these things in-process to save some time.

**Comment by rpspringuel** [comment]
Okay, other than the test fails that came from running the 5.1.1 tests against 5.0.2, testing worked on Ubuntu.

**Pull request merged**
