### PR TITLE
Made find and xargs into environment variables.

### LINKED ISSUE #126: Problems with tests on latest develop
When running the tests on the latest develop I'm getting a bunch of errors which don't make much sense to me:

```
error: can't open file {} for reading___________________] 129/437
{} : FAIL - Failed to compile {}
grm: cannot remove ‘gabc-dump/should-fail/bad-hepisema-2.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-hepisema-2.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-hepisema-2.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-hepisema-3.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-hepisema-3.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-hepisema-3.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-hepisema-4.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-hepisema-4.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-hepisema-4.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-hepisema-5.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-hepisema-5.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-hepisema-5.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-hepisema.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-hepisema.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-hepisema.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-liquescence.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-liquescence.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-liquescence.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-macro.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-macro.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-macro.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-secondary-clef-2.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-secondary-clef-2.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-secondary-clef-2.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-secondary-clef.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-secondary-clef.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-secondary-clef.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-shape.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-shape.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-shape.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-sign.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-sign.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-sign.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-slur.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-slur.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-slur.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-special-sign.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-special-sign.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-special-sign.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-staff-lines.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-staff-lines.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-staff-lines.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-unicode.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-unicode.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-unicode.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-var-slur-end.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-var-slur-end.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-var-slur-end.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-var-slur.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-var-slur.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-var-slur.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-vowel-file/bad-vowel-file.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-vowel-file/bad-vowel-file.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad-vowel-file/bad-vowel-file.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad_translation_centering.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad_translation_centering.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad_translation_centering.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad_translation_centering_2.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad_translation_centering_2.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/bad_translation_centering_2.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/center-in-elision.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/center-in-elision.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/center-in-elision.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/clef-too-high.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/clef-too-high.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/clef-too-high.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/Dominican-bar-too-high.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/Dominican-bar-too-high.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/Dominican-bar-too-high.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/elision-initial.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/elision-initial.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/elision-initial.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/nested-elision.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/nested-elision.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/nested-elision.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/pitch-too-high.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/pitch-too-high.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/pitch-too-high.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-over-ledger-2.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-over-ledger-2.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-over-ledger-2.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-over-ledger.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-over-ledger.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-over-ledger.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-overbrace-2.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-overbrace-2.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-overbrace-2.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-overbrace.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-overbrace.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-overbrace.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-slur-2.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-slur-2.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-slur-2.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-slur.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-slur.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-slur.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-under-ledger-2.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-under-ledger-2.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-under-ledger-2.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-under-ledger.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-under-ledger.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-under-ledger.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-underbrace-2.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-underbrace-2.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-underbrace-2.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-underbrace.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-underbrace.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unclosed-underbrace.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unopened-over-ledger.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unopened-over-ledger.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unopened-over-ledger.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unopened-overbrace.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unopened-overbrace.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unopened-overbrace.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unopened-slur.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unopened-slur.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unopened-slur.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unopened-under-ledger.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unopened-under-ledger.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unopened-under-ledger.dump-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unopened-underbrace.gabc.out-’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unopened-underbrace.dump’: No such file or directory
grm: cannot remove ‘gabc-dump/should-fail/unopened-underbrace.dump-’: No such file or directory
```

Obviously on the first is an actual test fail, but the file name given (`{}`) makes no sense.  The rest look like the clean-up algorithm looking for the files which would be produced by a successful test while trying to clean-up after a test which should fail (and thus not produce those files).

### PR DESCRIPTION
**Pull request by henryso**
Fixes #126.

I happened to do this on top of a different submission, but I might as well include that here.

@rpspringuel Please try this out with your XARGS setting and merge if if successful.

### CODE REVIEW

**Comment by rpspringuel** [comment]
I'm running the tests and things are close enough to complete for me to be sure they're working fine.

Looking at the new script, it seems that it's mostly just a skeleton so far.  Do you want to fill that in before this gets merged or do you prefer to fill it in later?

**Comment by henryso** [comment]
The new script is fully usable at this point, at least on my computer.

**Comment by rpspringuel** [comment]
I haven't actually tested it, I was just looking at the code and saw a case tree that didn't seem to be doing a whole lot (or have a whole lot going on after it) at first glance.  After looking at it again, I see that I missed the surrounding while loop (and the fact that the functional bits happen at the beginning of said loop).

**Comment by henryso** [comment]
It's a simple script.  I was considering folding it into gregorio-test.sh, but there's no need to complicate that script for this one, so I just added it.

**Pull request merged**
