### PR TITLE
Tests for parenthesized figures

### PR DESCRIPTION
**Pull request by henryso**
Tests gregorio-project/gregorio#1475.
For gregorio-project/gregorio#1476.

This pulls in some commits from @rpspringuel that made it into my repository.  Hopefully this doesn't cause issues, but the tests pass as of this commit.

This includes an update to the latest version of the Alegreya font because the old one wasn't working so well with Tex Live 2019.

### CODE REVIEW

**Comment by henryso** [comment]
@rpspringuel After merging the changes form internalizing gsp-default, the `tex-output/bugs/fix-1461/fix-1461.tex`.  This test attempts to reload the default spacing with `\greloadspaceconf{default}`, and this fails because at that point `@` is not a letter and `\gre@declarefileversion` stops at `\gre`.  Of course, the rest of the file will fail to load as well.  What do you think is the correct fix here?

**Comment by rpspringuel** [comment]
I'll take a look on Monday.  Too busy today to spare the time needed to look at this.

**Comment by rpspringuel** [comment]
Something's wrong with my MacPorts installation.  I'm not going to be able to do any real testing until I figure out what.

**Comment by henryso** [comment]
Is there a new correct way to reset the spacing to default after these new changes?

**Comment by rpspringuel** [comment]
`\greloadspaceconf{default}` is supposed to be the way to reload the default spacing configurations.  I think you're running into an aspect of [the problem](https://github.com/gregorio-project/gregorio/pull/1467#issuecomment-506451887) I noted about reloading the defaults and never got around to fixing.  Clearly we need to finish fixing #1467 in order to unblock things.

**Comment by rpspringuel** [comment]
Well, my MacPorts stuff is all fixed now, so I've started to look at this.  However, I'm running into bad `\ifnum` complaints (missing number and missing comparison) when trying to typeset scores using your changes (even ones which are not the failing test you noted).  That's making it hard to diagnose and fix the problem you noted.  @henryso, can you provide me with a known good test?

In the meantime, I'm going to try to solve the gsp-default stuff on another branch.

**Comment by henryso** [comment]
This may be an indicator of some deeper issues.  All the tests here except the one that attempts to reload the defaults was working on my system.  I probably need to review your changes, merge them and try to get this working again.

**Comment by henryso** [comment]
Ok, I merged your changes and the tests all pass with really minor font differences from me upgrading Alegreya.

**Comment by rpspringuel** [comment]
I'm getting 9 tests which fail on small font differences, but the new tests look good.  I haven't physically looked at all the changed tests (just the failed ones), but I'm not opposed to merging this as is.

**Pull request merged**
