### PR TITLE
New test showing the splitting of the offset limits.

### PR DESCRIPTION
**Pull request by rpspringuel**
This result will change when gregorio-project/gregorio#921 is fully fixed, but I think this shows that what I'm trying to do works.

Corresponds to gregorio-project/gregorio#937

### CODE REVIEW

**Comment by rpspringuel** [comment]
I've modified the test to show the mirror case.  I haven't accepted revised results yet, however, for two reasons:

1. this will only really be interesting once the final revisions for gregorio-project/gregorio#921 are accepted.
2. I've been unable to modify the test case sufficiently enough at this point to trigger all the code I've written.  In the mirror case the notes of the following syllable don't stick out in front of the text enough to create a collision when the bar gets pushed to the right.  Suggestions as to how to get that kind of hanging are appreciated.

**Comment by eroux** [comment]
For an example see https://github.com/gregorio-project/gregorio/pull/932#issuecomment-185676758 : `{3}3333333333(g) *(;) {}4444(gxgf)`

**Comment by eroux** [comment]
Sorry, I relize you already had this one, well I think this is the most extreme example I can think of... Adding some kerns would be possible, but I don't think there's any use... If the example you have works fine, then let's keep it this way

**Comment by rpspringuel** [comment]
I found the way to make that test work.  I simply put the bar in the same word as the surrounding syllables: `{3}3333333333(g)*(;){}4444(gxgf)`

It may not be terribly realistic, but it allows the code to be tested.

**Pull request merged**
