### PR TITLE
Changes which result from rpspringuel/gregorio@2f7f63b

### PR DESCRIPTION
**Pull request by rpspringuel**
Corresponds to gregorio-project/gregorio#1058

### CODE REVIEW

**Comment by eroux** [comment]
Well, I think it does look nice... but I'm no big user of Gregorio... so I don't know, maybe we should ask the list?

**Comment by rpspringuel** [comment]
If you look at the [Salve](https://github.com/rpspringuel/gregorio-test/blob/feature/fontdimen/tests/tex-output/SalveReginaOP/SalveReginaOP.pdf) there are a couple of places ("Et Jesus" and "post hoc exsilium) where I feel that things get a bit tight.  The tightness is even more apparent in some of the artificial tests where a long syllable is associated with a fairly compact set of notes (e.g. [auto-fusion](https://github.com/rpspringuel/gregorio-test/blob/feature/fontdimen/tests/gabc-dump/glyphs/auto-fusion.pdf) where you can barely tell where one "word" ends and the next begins on the second and 4th lines).

My gut feeling is that this has to do with the relative size of the spaces between syllables and between words, and the difference when the between word spacing is controlled by the notes vs. the text.

**Comment by eroux** [comment]
Well, it's a bit difficult, because I think the font we use in tests has small spaces in all cases... But that's a very difficult question... perhaps we would have less problems by expressing these spaces in `em` or `ex` units? And put the `\fontdimen` thing in a Tips & Tricks "How to get the same interword spaces in scores and text"?

**Comment by rpspringuel** [comment]
Using `em` and/or `ex` though is running into the problem you pointed out in gregorio-project/gregorio#1036: the relation between those units and `\fontdimen2` is not the same for all fonts.  I can make the switch, but I thought you wanted something specifically dependent on `\fontdimen2` for `interwordspace`.

Perhaps the better question is "what is the purpose of the defaults?"  Are we trying to demonstrate how to set-up various relationships while still retaining somewhat reasonable values?  If so then these defaults are fine.  Are we trying to match some sample?  If so, we need to define what that sample is so that changes can be compared against it.  Are we trying to create some exemplar which demonstrates GregorioTeX at it's finest?  If so, we should specify what that exemplar is, including the fonts being used, so that we can look specifically at it when deciding whether a change improves things or not.  Or are we trying to pick values which look decent for a large number of scores?  This last case is the hardest to figure out because what works for one score might not work for another.

**Comment by eroux** [comment]
For the first part of the question: indeed, specifying an `em` size won't use the space defined by the font, but it will be more coherent between different fonts, and will look better on fonts with very small spaces like the one we use in tests. That's not what I wanted initially, but we have to do with how things are...

I think the second question is a good one: in my experience, only two very big projects change the space settings, I don't know any other user doing it, and some users are even very reluctant to do it, so I think the defaults should look decent for a large number of scores, fonts, sizes, etc. because many users change that and expect the defaults to still be ok. GregorioTeX at its finest can only be achieved after tweaking some values according to the style, font, etc. What do you think?

**Comment by rpspringuel** [comment]
Okay, If I'm to set defaults based on `em` and/or `ex` how big should they be?  For Allegreya (the test font) `\fontdimen2` is a bit less than half of 1ex which is in turn a bit less than half of 1em.  Though perhaps the answer to this question is best settled after considering the below.

> GregorioTeX at its finest can only be achieved after tweaking some values according to the style, font, etc.

For sure, the only reason I haven't done such tweaking for my own projects, is because so far I've only been doing little things here and there and don't have a unified style yet.  The time investment simply doesn't make sense for a one-off.

> I think the defaults should look decent for a large number of scores, fonts, sizes, etc. because many users change that and expect the defaults to still be ok.

Thinking about this, it seems to be a reasonable goal, but one which is too nebulously defined to be used a bench mark in making decisions about whether a particular change to the defaults is an improvement or not.  Perhaps what we need is a small stable of scores which are typeset with a variety of fonts.  Then when making a change we could reference that stable to evaluate whether the change is an overall improvement or not.

**Comment by eroux** [comment]
The idea of a small set of score with different fonts is very good I think maybe it's best to put it as an option in the repository as it will require different fonts that I'm sure sure have their place in the test repository, but it would allow to have good samples. Maybe some scores with a lot of text, maybe some with more meilsma, etc. In terms of ex and em, let's choose something that makes slightly less than the current spaces of develop for LinLibertine... What do you think?

**Comment by rpspringuel** [comment]
If each font/score pair is unique, then I'd say that we can simply put them in the examples directory of the main repository where they can serve two purposes.

However, if we want to use the same score with several different fonts, then I'd make a separate folder for them in the test repository.  I don't think that I would make them runable from the primary test script, but a separate script which compiled the samples and then created an A/B side-by-side view for the purposes of comparison would be nice.

For the spaces, current develop has `interwordspacetext` at 0.38cm, which is just a hair bigger than 1em for 10pt Linux Libertine.  How does setting `interwordspacetext` to 1ex sound as a starting point?  That would be a little less than half of it's current value, and a little less than twice the values currently committed.

**Comment by eroux** [comment]
1ex sounds good indeed! I think a few scores with several fonts in the test repo is a good idea

**Comment by rpspringuel** [comment]
Changes are up.  I'll do the Tips'n'Tricks page later.

**Comment by eroux** [comment]
I think it looks good, thanks a lot! ok to merge

**Pull request merged**
